pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        // Public repo example; if private, set credentials in the job config.
        git branch: 'main', url: 'https://github.com/Ashraf-Magdy-Mostafa/alx-backend-python.git', credentialsId: 'github-creds'
      }
    }
    stage('Test') {
      steps {
        sh '''
          python -m pip install --upgrade pip || true
          if [ -f messaging_app/requirements.txt ]; then
            pip3 install -r messaging_app/requirements.txt
          else
            pip3  install pytest
          fi
          pytest --junitxml=pytest.xml
        '''
      }
    }
  }
  post {
    always {
      junit 'pytest.xml'
    }
  }
}
